---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source: embed
---

```{r setup, include = FALSE}
# Load required libraries for the assignment

library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r, include = FALSE}
# Load ny_noaa dataset, wrangle data, and reduce the n to a random sample of 5,000 weather observations.

noaa_df = ny_noaa %>%
  janitor::clean_names() %>%
  separate(date, into = c("year", "month", "day"), sep = '-') %>%
  mutate(month = as.numeric(month),
         year = as.factor(year),
         month = month.abb[month],
         month = factor(month, levels = month.abb),
         tmax = as.numeric(tmax),
         tmin = as.numeric(tmin),
         prcp = as.numeric(prcp),
         snow = as.numeric(snow),
         prcp2 = prcp/10,
         max_temp = tmax/10,
         min_temp = tmin/10) %>% 
  filter(
    year %in% 2000:2010,
   !is.na(min_temp),
   !is.na(max_temp),
   !is.na(prcp),
   !is.na(snow)) %>% 
  sample_n(5000)
```

## Temperature

### Mean temperature range per weather station
```{r}
minmax_temp = noaa_df %>%
  group_by(id) %>%
  summarise(c = mean(min_temp), h = mean(max_temp)) %>%
  mutate(id = forcats::fct_reorder(id, c)) %>% 
  plot_ly(alpha = 0.5, colors = "viridis") %>%
  add_segments(
    x = ~c, y = ~id,
    xend = ~h, yend = ~id, 
    showlegend = FALSE) %>%
  add_markers(
    x = ~c, y = ~id, 
    name = "Minimum temperature"
  ) %>%
  add_markers(
    x = ~h, y = ~id, 
    name  = "Maximum temperature"
  ) %>%
  layout(xaxis = list(title = "Mean Minimum and Maximum temperature per Weather Station"),
         yaxis = list(title = "Weather Station"))

minmax_temp
```

## Weather Events {.tabset .tabset-fade}

### Precipitation

Distribution of monthly rain

```{r}
prcp = noaa_df %>%
  mutate(text_label = str_c("Precipitation: mm ", prcp2, "\nSnowfall: mm ", snow),
         ) %>% 
  plot_ly(
    x = ~month, y = ~prcp2, type = "scatter", mode = "markers",
    color = ~id, text = ~text_label, alpha = 0.5, colors = "viridis") %>% 
  layout(xavis = list (title = "Month"),
    yaxis = list(title = "Precipitation (mm)"))

prcp
```


### Snow

Count of yearly days with snow per weather station

```{r}
snow = noaa_df %>%
  group_by(id) %>%
  mutate(snow_day = if_else((snow == "0"),"0","1"),
         snow_total = sum(as.numeric(snow_day))) %>% 
  plot_ly(
    x = ~year, y = ~snow_total, type = "bar",
    color = ~id, alpha = 0.5, colors = "viridis") %>% 
  layout(xavis = list (title = "Year"),
    yaxis = list(title = "Total days of snowfall"))

snow
```